
name: 2

on: [workflow_dispatch]
 

jobs:
  my_job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
 
 
      - name: checking
        run: echo "Done"
    
      - name: Checking helm version   
        run: helm version 
 
      - name: Checking direcotyr   
      - run: |
               pwd
               cd /home/rocky/pro/prometheus
 
      - name: Upgrading the helm chart
        run: helm upgrade mygrafana . 
        

