
name: 2

on: [workflow_dispatch]
 

jobs:
  my_job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
 
 
      - name: checking
        run: echo "Done"
    
      - name: Checking helm version   
        run: helm version 
 
      - name: Checking direcotyr   
        run:  cd /home/rocky/pro/grafana/
        
 
      - name: Upgrading the helm chart
        run: | 
          pwd
          cd /home/rocky/pro/grafana/
          helm upgrade mygrafana . 
        

